# Generated by Django 5.1.6 on 2025-02-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'verbose_name_plural': 'Blog Enteries'},
        ),
        migrations.AddField(
            model_name='blogentry',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
